const RESTARTABLE_READ_ONLY_REQUEST_TYPES = new Set([
  'pluginQuery',
  'executeRawSQL',
  'getSchema',
  'getAvailableYears',
  'getMemberActivity',
  'getHourlyActivity',
  'getDailyActivity',
  'getWeekdayActivity',
  'getMonthlyActivity',
  'getYearlyActivity',
  'getMessageLengthDistribution',
  'getMessageTypeDistribution',
  'getTimeRange',
  'getMemberNameHistory',
  'getCatchphraseAnalysis',
  'getLanguagePreferenceAnalysis',
  'getMentionAnalysis',
  'getMentionGraph',
  'getLaughAnalysis',
  'getClusterGraph',
  'getRelationshipStats',
  'getAllSessions',
  'getSession',
  'getChatOverview',
  'getMembers',
  'getMembersPaginated',
  'searchMessages',
  'deepSearchMessages',
  'getMessageContext',
  'getSearchMessageContext',
  'getRecentMessages',
  'getAllRecentMessages',
  'getConversationBetween',
  'hasSessionIndex',
  'getSessionStats',
  'getAllIndexStats',
  'getSessions',
  'getSessionsByTimeRange',
  'getRecentChatSessions',
  'searchSegments',
  'getSegmentMessages',
  'getSegmentSummaries',
])

export function isRestartableReadOnlyRequestType(type: string): boolean {
  return RESTARTABLE_READ_ONLY_REQUEST_TYPES.has(type)
}
